version: '3.7'
services:
    mysql_cluster_db1:
        build: 
            context: .
            dockerfile: ./mysql/Dockerfile
        container_name: "mysql_cluster_db1"
        hostname: "db1"
        # restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root123
        ports:
            - "3301:3306"
        volumes:
            - ./db/mysql1:/var/lib/mysql
            - ./etc/mysql1:/etc/mysql/conf.d
            # - ./mysql/apt-config/mysql-apt-config_0.8.24-1_all.deb:/tmp/
        networks:
            - mysql_cluster
    mysql_cluster_db2:
        build: 
            context: .
            dockerfile: ./mysql/Dockerfile
        container_name: "mysql_cluster_db2"
        hostname: "db2"
        # restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root123
        ports:
            - "3302:3306"
        volumes:
            - ./db/mysql2:/var/lib/mysql
            - ./etc/mysql2:/etc/mysql/conf.d
            # - ./mysql/apt-config/mysql-apt-config_0.8.24-1_all.deb:/tmp/
        networks:
            - mysql_cluster
    mysql_cluster_db3:
        build: 
            context: .
            dockerfile: ./mysql/Dockerfile
        container_name: "mysql_cluster_db3"
        hostname: "db3"
        # restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root123
        ports:
            - "3303:3306"
        volumes:
            - ./db/mysql3:/var/lib/mysql
            - ./etc/mysql3:/etc/mysql/conf.d
            # - ./mysql/apt-config/mysql-apt-config_0.8.24-1_all.deb:/tmp/
        networks:
            - mysql_cluster
    nginx:
        image: nginx:latest
        container_name: "mysql_cluster_nginx"
        hostname: "app1"
        ports:
            - "83:80"
        restart: always
        volumes:
            # - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./projects/:/var/www/projects"
        depends_on:
            - php8.2
            - mysql_cluster_db1
            - mysql_cluster_db2
            - mysql_cluster_db3
        networks:
            - mysql_cluster
    php8.2:
        build: 
            context: .
            dockerfile: ./php8.2/Dockerfile
        container_name: "mysql_cluster_php8.2"
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            # - "./etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
            - "./projects/:/var/www/projects"
        networks:
            - mysql_cluster
networks:
    mysql_cluster:
        driver: bridge
